version: '3.8'

services:
  apigateway:
    build: ./ApiGateway
    ports:
      - "7001:80"
    depends_on:
      - ordermanagement
      - paymentprocessing
      - productcatalog
      - shoppingcart
      - usermanagement

  ordermanagement:
    build: ./OrderManagement
    ports:
      - "7002:80"

  paymentprocessing:
    build: ./PaymentProcessing
    ports:
      - "7003:80"

  productcatalog:
    build: ./ProductCatalog
    ports:
      - "7004:80"

  shoppingcart:
    build: ./ShoppingCart
    ports:
      - "7005:80"

  usermanagement:
    build: ./UserManagement
    ports:
      - "7006:80"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    environment:
      SA_PASSWORD: YourStrong(!)Password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
#     volumes:
#       - sql_data:/var/opt/mssql

# volumes:
#   sql_data:
